### PR TITLE
Change title of dashboard and login pages

### LINKED ISSUE #3: Rename Page Titles
**Describe the bug**
Dashboard and login pages have different page titles.

**Expected behaviors'**
Both pages have page different titles. Titles should be changed.
**Screenshots**

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by savindumahasen**
## Purpose

The purpose of this PR is to fix #3

## Goals
To rename the page titles

## Approach
Renamed the approach

### CODE REVIEW

File: dashboard.php [hunk 1]
```diff
@@ -2,7 +2,7 @@
 <html lang="en">
 <head>
     <meta charset="UTF-8">
-    <title>LMS-Dashboard</title>
+    <title>SACK-Dashboard</title>
```
Comment (gajindubandara) [inline dashboard.php]: Change the title to "SACK-LMS"

File: login.php [hunk 2]
```diff
@@ -2,7 +2,7 @@
 <html lang="en">
 <head>
     <meta charset="UTF-8">
-    <title>LMS-Login</title>
+    <title>SACK-Login</title>
```
Comment (gajindubandara) [inline login.php]: Do the same as in the above file

**Review by gajindubandara — CHANGES_REQUESTED** [review]
